//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水,沃,湃,衍,澳,溜,谷,沉,沈,瀑,溉,沐,沛,沙,漆,沟,溅,溺,没,沧,沦,沥,粱,沫,沪,沮,河,溪,梁,溯,治,溢,油,沸,沿,沾,沽,沼,滚,益,泄,滞,泉,泊,滓,泌,滕,暴,滋,法,隶,泛,泞,泡,波,泣,泥,注,泪,滴,渠,泰,滩,泳,泵,满,泻,泼,泽,漩,漫,洒,洗,漠,洛,踏,洞,洁,溃,漾,漱,洋,滨,洲,漏,活,溥,洽,洼,派,源,津,漓,洪,演,潮,潭,浓,浑,潦,黍,浙,浆,浇,浅,柒,染,济,浊,测,海,浴,滤,酒,浸,滥,浦,湘,潜,灌,萍,澎,浮,浪,浩,涎,涌,涉,消,流,涂,溶,涝,涛,涕,澈,范,涯,涮,澄,涩,涨,涧,润,涤,涣,涡,湿,茫,涵,澜,液,淌,淋,冰,淆,淀,淘,犀,淑,淮,激,淫,淤,淡,淹,濒,添,混,深,淳,渔,渗,渐,澡,渊,清,游,渺,渴,港,温,滑,渤,渡,永,渣,汉,潘,桼,滔,汁,汇,汛,汞,江,湾,汗,汪,尿,漂,池,污,汤,汹,湖,汽,汰
        ///手,挺,挽,挨,挫,挪,振,挡,挠,挣,搀,挥,挤,挚,挟,挑,挖,按,挎,持,撼,挂,指,捺,捻,撤,捶,捷,撩,撮,播,撬,据,撰,撵,撒,捧,换,捣,捡,捞,损,撇,捕,捐,捎,捏,捌 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdjList {
            get {
                return ResourceManager.GetString("AdjList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扯,手止
        ///屮,屮
        ///彻,彳切
        ///徹,育攵
        ///撤,手徹
        ///澈,水徹
        ///尘,小土
        ///臣,臣
        ///忱,心冘
        ///沉,水冗
        ///辰,厂二
        ///陈,阜东
        ///晨,日辰
        ///闯,门马
        ///衬,衣寸
        ///称,禾尔
        ///趁,走昣
        ///铛,金当
        ///撑,手掌
        ///丞,子廾
        ///成,戈
        ///呈,口王
        ///承,手人
        ///诚,言成
        ///城,土成
        ///乘,禾北
        ///惩,征心
        ///程,禾呈
        ///澄,水登
        ///橙,木登
        ///逞,辶呈
        ///秤,禾平
        ///吃,口乞
        ///蚩,屮虫
        ///嗤,口蚩
        ///痴,疒知
        ///弛,弓也
        ///池,水也
        ///驰,马也
        ///迟,辶尺
        ///持,手寺
        ///匙,是匕
        ///尺,尺
        ///侈,人多
        ///齿,止人凵
        ///耻,耳止
        ///彳,彳
        ///斥,斤
        ///赤,土火
        ///翅,支羽
        ///充,子儿
        ///冲,冫中
        ///虫,虫
        ///崇,山宗
        ///宠,宀龙
        ///抽,手由
        ///仇,人九
        ///绸,糸周
        ///畴,田寿
        ///愁,秋心
        ///稠,禾周
        ///筹,竹寿
        ///酬,酉州
        ///丑,又
        ///臭,自犬
        ///出,屮凵
        ///初,衣刀
        ///刍,勹屮
        ///除,阜余
        ///厨,厂豆寸
        ///锄,金助
        ///雏,刍隹
        ///橱,木厨
        ///础,石出
        ///储,人诸
        ///楚,林足
        ///处,夂卜
        ///触,角虫
        ///矗,直
        ///揣,手耑
        ///川,川
        ///リ,リ
        ///阿,阜可
        ///啊,口阿
        ///哎,口艾
        ///哀,衣口
        ///唉,口矣
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string decomp {
            get {
                return ResourceManager.GetString("decomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行,彳丁
        ///土,土
        ///圓,口員
        ///痿,疒委
        ///旁,立方
        ///瓣,辛瓜
        ///簸,箕皮
        ///誡,言戒
        ///瓤,瓜襄
        ///歉,兼欠
        ///庸,庚用
        ///瘟,疒昷
        ///街,行圭
        ///誕,言延
        ///衩,衣叉
        ///歷,禾止厂
        ///衣,衣
        ///瘩,疒荅
        ///圪,土乞
        ///誆,言匡
        ///圭,土
        ///武,止弋
        ///歧,止支
        ///此,止匕
        ///麻,广林
        ///瘸,疒加肉
        ///正,一止
        ///源,水原
        ///助,且力
        ///像,人象
        ///予,予
        ///檀,木亶
        ///加,力口
        ///二,一
        ///僉,人口亼
        ///隱,急工阝爪
        ///井,井
        ///賴,束負
        ///聿,肀二
        ///賺,貝兼
        ///隹,隹
        ///窄,穴乍
        ///僚,人尞
        ///賽,宀弄貝
        ///亡,人乚
        ///聊,耳卯
        ///簷,竹詹
        ///交,交
        ///檬,木蒙
        ///隋,阝左月
        ///亭,京丁
        ///候,侯
        ///聚,取人
        ///檸,木寧
        ///穩,禾隱
        ///力,力
        ///隙,阝日小
        ///人,人
        ///僻,人辟
        ///藏,艹臧
        ///弱,弓二
        ///蹈,足舀
        ///薄,艹溥
        ///魏,委鬼
        ///張,弓長
        ///薛,艹垖辛
        ///臽,刀臼
        ///魔,麻鬼
        ///醬,將酉
        ///魚,魚
        ///董,艹重
        ///薯,艹署
        ///弓,弓
        ///活,水舌
        ///弗,弔
        ///弔,弓
        ///引,弓
        ///弊,敝廾
        ///弋,弋
        ///率,玄十冫
        ///玄,人幺
        ///王,王
        ///憤,心賁
        ///痢,疒利
        ///弄,王廾
        ///壤,土襄
        ///攵,攵
        ///攴,十又
        ///糖,米唐
        ///攸,人攵
        ///士,士
        ///鍬,金秋
        ///糟,米曹
        ///疒,疒
        ///灌,水雚
        ///某,甘木
        ///柒,水七木
        ///蘸,艹酉焦
        ///支,十又
        ///攮,手囊
        ///鍁,金欣
        ///查,木旦
        ///壁,辟土
        ///柬,束八
        ///糸 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string decompT {
            get {
                return ResourceManager.GetString("decompT", resourceCulture);
            }
        }
    }
}
